### ISSUE TITLE
lily sync err

### ISSUE THREAD

**Issue by xiaoyuaiheshui** [filecoin-project/lily#1064]
### Describe the bug:
After I start these tasks, my synchronization height will become very slow, and even can't reach the latest height, so I will fall behind a lot. Is there any configuration I haven't turned on?

Here are my watch tasks

		"Tasks": [
			"miner_sector_infos_v7"
		],
		"Running": true,

		"Tasks": [
			"miner_sector_event"
		],
		"Running": true,

		"Tasks": [
			"block_header"
		],
		"Running": true,

		"Tasks": [
			"miner_current_deadline_info"
		],
		"Running": true,
		"Tasks": [
			"chain_power"
		],
		"Running": true,

		"Tasks": [
			"verified_registry_verifier"
		],
		"Running": true,

lily sycn wait:
Worker: 38817; Base: 2177824; Target: 2177862 (diff: 38)
State: message sync; Current Epoch: 2177836; Todo: 26
Validated 0 messages (0 per second)

My machine configuration:
AMD EPYC 7302
Mem: 2T
nvme: 15T

**Comment by LINJINTIANDE** [comment]
There is no way to configure one machine to run miner series tasks in parallel with other tasks. It is recommended that multiple machines be distributed

**Comment by xiaoyuaiheshui** [comment]
One question I didn't understand: does Lily have a separate worker process? How do I run on other machines? Do I need to resynchronize the height

**Comment by xiaoyuaiheshui** [comment]
@LINJINTIANDE

**Comment by LINJINTIANDE** [comment]
https://lilium.sh/ First read the document carefully, which has a distributed introduction

**Comment by frrist** [comment]
A couple of things you can do to improve performance:
- set `--blockstore-cache-size` and `--statestore-cache-size` on the `daemon` command. e.g. 
`lily daemon --statestore-cache-size=10000000 --blockstore-cache-size=10000000` These values must be set appropriately based on your system resources. If you have 2TB of RAM then the values I have provided here should work.
- Run a single job with all tasks enabled instead of a job for each task. If you are watching the chain start a single watch job with all tasks enabled.
- Ensure the node caught up syncing before starting a job.
- As @LINJINTIANDE mentioned, run lily using the distributed indexing pattern described here: https://lilium.sh/software/lily/operation/#distributed-tipset-workers. This will require multiple machines. The [docker-compose](https://github.com/filecoin-project/lily/blob/master/docker-compose.yml) file provides an example of how to achieve this.
