### ISSUE TITLE
Actor Events Support

### ISSUE THREAD

**Issue by birdychang** [filecoin-project/lily#1125]
[FIP-0049](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0049.md#receipt-events_root-optionality) - actor events

- PLDW

  - add events root column to receipts and vm messages

- Filcryo
  
  - need to enable eth rpc so that events root is saved in the blockstore

This is how we can parse the receipts event root: https://github.com/filecoin-project/lotus/blob/4fd81e0c58ba075c1410abf29469bc0ba1081124/chain/events/filter/event.go#L452-L459

Each entry of the AMT is one of these: https://github.com/filecoin-project/lotus/blob/4fd81e0c58ba075c1410abf29469bc0ba1081124/chain/types/event.go#L7

Here is how lotus persists this information to its own optional internal sqlite database: https://github.com/filecoin-project/lotus/blob/master/chain/events/filter/index.go

Looks like @iand did the bulk of this work on this, 

@kasteph I would reach out to him for guidance on how we should model this data. I would expect the conversion of https://github.com/filecoin-project/lotus/blob/4fd81e0c58ba075c1410abf29469bc0ba1081124/chain/types/event.go#L23 to be something we handle in post processing

Given the above, we should aim to mimic the schema Lotus uses. If we do that right we might be able to implement a similar API to lotus over the tables

**Comment by kasteph** [comment]
I reached out to @iand and we agreed that there's no need to depart [from the schema in Lotus](https://github.com/filecoin-project/lotus/blob/4fd81e0c58ba075c1410abf29469bc0ba1081124/chain/events/filter/index.go#L35-L53). We can use the same schema and use a BRIN index for Timescale since it will be much smaller than a B-Tree index. However, if we use BRIN, we basically won't be able to do backfills since it will then perform very poorly. So maybe a B-Tree would be good enough since we don't have size constraints like Lotus does.

**Comment by birdychang** [comment]
Don't think we need to worry about TimescaleDB too much. It will have a retention policy. I would guess most queries should still go to BigQuery.

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/1127
