### ISSUE TITLE
Investigate missing data in Analysis Production using Visor (lily) v0.7.1

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#596]
Reported by @hsanjuan:
Using an independent backfill process, we noticed new data was approx 2x larger than what lily was inserting. First image from now, second from some hours ago:

Now:
![image](https://user-images.githubusercontent.com/305332/124818241-c9b24c00-df38-11eb-951c-5dd9a0b00385.png)

Some hours ago:
![image (1)](https://user-images.githubusercontent.com/305332/124818292-d8006800-df38-11eb-95e9-aab2e86084bf.png)

Observing that the total amount of prove commits goes from 3M to 11M.

I would like to know if:
- There is a problem (duplicate rows being inserted)
- ~Lily is dying and restarting, or skipping epochs so often that this is the result.~ Determined that lily does not seem to be restarting.

Running docker image `filecoin/sentinel-visor:v0.7.1` with the following tasks:
```
visor watch --storage=db --confidence=5 --tasks=blocks, messages, chaineconomics, actorstatesraw, actorstatespower, actorstatesreward, actorstatesinit, actorstatesmarket, actorstatesmultisig, msapprovals
```
(spaces added for readability)

**Comment by placer14** [comment]
Logs from last 4 hours on this production container: https://app.logz.io/#/goto/e883caf88f47419fba64e22b4072de29?switchToAccountId=104138

Found 9,634 processing errors in the DB: https://gist.github.com/placer14/3f0f4674fd5a28c254ce9d7cce75795c

More "block not found".
Also saw "failed to extract parsed actor state: extracting miner sector changes: diffing miner sectors: node leaves have different numbers of values (prev=0, cur=32)"", ""Address"": ""f01040006""".
And a bunch of empty reasons.

**Comment by frrist** [comment]
Currently puzzling over where the Status Information message: `tipset did not have expected parent or child` is coming from. From what I can tell that string doesn't exist in the visor code base...

The other status information message: `indexer not ready` means that the indexer is taking longer than one epoch to process, this happens when writes to storage are slow.

| Height| StateRoot | Name | Task | Start | End | Status | Status Information |
|-------|-----------|------|------|-------|-----|--------|--------|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|msapprovals|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|messages|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|actorstatesreward|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|actorstatesraw|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|actorstatespower|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|actorstatesmultisig|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|actorstatesminer|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|actorstatesmarket|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912583|bafy2bzacec6usbks2linln5lfepj3yabvat2jn3w2bwjdrbjj5rkvtnbwfcgi|watch_1625139608|actorstatesinit|2021-07-07 19:42:30.450063|2021-07-07 19:42:30.450063|SKIP|tipset did not have expected parent or child|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|msapprovals|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|messages|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|chaineconomics|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|blocks|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|actorstatesreward|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|actorstatesraw|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|actorstatespower|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|actorstatesmultisig|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|actorstatesminer|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|actorstatesmarket|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912582|bafy2bzaceciqiaiksgzgigthemwttnekdi5ohjp3nez3nb7bvbo7twkswlemo|watch_1625139608|actorstatesinit|2021-07-07 19:42:00.580703|2021-07-07 19:42:00.580703|SKIP|indexer not ready|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|msapprovals|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|messages|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|actorstatesreward|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|actorstatesraw|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|actorstatespower|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|actorstatesmultisig|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|actorstatesminer|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|actorstatesmarket|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|
|912562|bafy2bzacecekbt62uuglqcywahehablqtdbcsaxgxb3lviaqicnjjdaecssds|watch_1625139608|actorstatesinit|2021-07-07 19:31:30.520561|2021-07-07 19:31:30.520561|SKIP|tipset did not have expected parent or child|

**Comment by frrist** [comment]
@placer14 I think this instance is running `filecoin/sentinel-visor:v0.7.2`, can you confirm?

**Comment by iand** [comment]
Closing due to age.
