### ISSUE TITLE
lily gap fill fails to populate specific height/task "successfully"

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#810]
### Describe the bug:
Attempting to gapfill a specific epoch/task results (in at least this case): 
- (a) to detect the gap, (producing a GAP report)
- (b) to fill the gap resulting in a FILLED gap report,
- (c) also resulting in an OK processing report,
- (d) and also not producing the data in the targeted table

### Steps to Reproduce:
Context: The specific datapoint I'm trying to reproduce is a TERMINATED sector event for miner `f0145784` and sector `2696` at epoch `1127325`.

0. Have a node with history back to the target epoch.
1. `lily walk` the heights 1127324 - 1127326 (to have surrounding heights for gapfind to work properly)
2. Observe 1127325 has the expected TERMINATED sector event datapoint.
3. Remove the datapoint. Remove all processing reports at the target height.
4. `lily gap find --storage filltest --name 20220106-uniquename-1127325 --from 1127324 --to 1127326 --tasks actorstatesminer`
5. Observe GAPs are detected.
6. `lily gap fill --storage filltest --name 20220106-uniquename-1127325 --from 1127324 --to 1127326 --tasks actorstatesminer`
7. Observe GAPs are now FILLED
8. Observe processing reports are OK for epoch, task
9. Observe missing datapoint.

**Comment by placer14** [comment]
A more recent confirmed case where this is occurring for `minerstatesactor` task at height `1195379`. Looking for RECOVERED event for `(miner_id = 'f020385' and sector_id =59791)`. That's `2021-10-13 23:29:30+00` or 85 days 17:24:38.051224 from this comment's timestamp.

**Comment by frrist** [comment]
This seems to suggest a divergence between the data extracted by the walk and gap-find commands. What database was the above run with?

**Comment by placer14** [comment]
This was reproduced in both the prod and staging DBs. (See `mainnet` and `walk-fill-testing` in the main DB cloud instance.

**Comment by frrist** [comment]
I am unable to connect to the `walk-fill-testing` instance due to permission errors.

**Comment by frrist** [comment]
I have attempted to debug this by using slightly different heights as my node doesn't have enough chain history to go back to the height specified in the OP. Here is what I did:

Run a walk for the miner task and export the miner_sector_events table to csv:
```
lily_mainnet walk --storage Database1 --name debug_for_mike_3 --from 1451556 --to 1451556 --tasks actorstatesminer --window 0
```
[walk_miner_sector_events.csv](https://github.com/filecoin-project/lily/files/7842399/walk_miner_sector_events.csv)

----------------------

Truncate database

----------------------

Manually enter a gap at height `1451556` for task `actorstatesminer`
Run a gap fill for the miner task and export the miner_sector_events table to csv:
```
lily_mainnet gap fill --tasks actorstatesminer  --from 1451556 --to 1451556 --storage Database1
```
[fill_miner_sector_events.csv](https://github.com/filecoin-project/lily/files/7842406/fill_miner_sector_events.csv)

Currently inspecting said files for where difference exist.

**Comment by frrist** [comment]
Height `1127324` is a null round.
Running: 
```
lily gap find --storage filltest --name somename --from 1127323 --to 1127325 --tasks actorstatesminer

lily gap fill --storage filltest --name someothername --from 1127323 --to 1127325 --tasks actorstatesminer
```
finds and fills the gaps, producing what I believe to be the expected terminated sector event:
```
height,miner_id,sector_id,state_root,event
1127325,f0145784,2696,bafy2bzacecc2qdua4irzh2f4rpl4zq5yktpguchmjvyemrjbpiv7p6rtlsxpg,SECTOR_TERMINATED
```

It is worth noting that there is *not* a one to one mapping between the heights in the processing reports table and the heights in the model tables. This is due to how expected consensus works. Messages at height N are applied in block N+1+(# of null rounds). So long as the processing reports table is treated as a source of truth for the work that has been performed, filling gaps in it will populate the correct models.

---------------------------

As an example:

Instruct the TipSet indexer to index all tasks for TipSet at height 100 (walk from 100 to 100)
Inspect database after job completes and see:
- processing report for each task is complete at height 100
- blocks table has height 100
- message and receipts  has height 101
- all actors have height 101

the data is correct in that:
- blocks were produced at height 100
- messages were included in block height 100 and executed at height 101 and produced a receipt at height 101
- actors state changed from 100 -> 101 and is reflected correctly at height 101

the problem is one would expect to only see state for height 100 in the database. Instead we see:
- height 100 for single tipset processors (blocks and consensus)
- height 101 for processes that accept two tipsets (to diff) since the change occurred when applying messages at height 100 and the result is in 101

**Comment by placer14** [comment]
I have not been able to confirm any cases where lily completed processing "successfully" without producing expected data (now that I better understand the null round edge cases which seem to be involved in many of the examples). Closing. (thx for feedback Forrest! 🙏 )
