### ISSUE TITLE
Failure to persist data to storage should include persistence error in processing report

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#920]
When persisting data to the storage fails, the processing report for that task is reported as SKIP: indexer not ready. It would be better if the `errors_detected` could include the reason for failure if there are more granular details avail.

This occurred for `actorstatesminer` for heights 1664323-1669213 in production DB. You can find the logs indicating something like

```
{"level":"error","ts":"2022-03-28T19:23:32.744Z","logger":"lily/chain","caller":"chain/indexer.go:506","msg":"persistence failed","current":1668805,"next":1668806,"task":"actorstatesminer","error":"dial tcp: i/o timeout"}
```

**Comment by frrist** [comment]
I'm not sure how to update the processing report in the event lily fails to communicate with the database. Generally that means lily is unable to communicate with the storage backend and thus cannot write any more information to it (but I think I could be misunderstanding the issue here). Logs are the next best thing. 

#871 has modified the indexer to return a fatal error and halt in the event persistence fails. It also fixed a bug that prevent error messages from being marshaled to json in the `errors_detected` column.

I'm going to close this as I think its less applicable after the refactor we landed. But feel free to reopen or continue conversation if I am mistaken in doing so.

**Comment by placer14** [comment]
FWIW, I'm not sure if this is still relevant. It's unclear whether persistent failures affect just the task, the job, or the whole daemon. If the task is able to persist a report indicating `SKIP: tipset not ready` I expect it could just as easily be `ERROR: io timeout` but I haven't looked at what context those reports are made from to know if this is possible. I'll wait and see how these changes affect things and revisit as needed. 🤝
