### ISSUE TITLE
Track Miner Deal Making protocol via survey job

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#989]
### Description
Track the deal-making protocol version used by miners: https://boost.filecoin.io/configuration#dealmaking

### Acceptance criteria
- [ ] create new table for data
- [ ] implement new job on survey command

**Comment by frrist** [comment]
closing, work tracking here https://github.com/orgs/filecoin-project/projects/55/views/1

**Comment by jacobheun** [comment]
@frrist it looks like this got closed out in favor of the project board but that's empty. Did this ever get picked up? From the [discussion](https://www.notion.so/pl-strflt/Boost-Metrics-Tracking-82347ac7123f40c4917316e6c3795bee) back in June it sounded like we were hoping to be able to kick off this work in July so I just wanted to follow up in case it fell off the radar.

**Comment by jacobheun** [comment]
@frrist we're happy to submit PR's to help get this landed if you can point us in the right direction for how this should integrate with lily/sentinel.

For additional context, we created a crawler, the [`boostx stats` command](https://github.com/filecoin-project/boost/blob/main/cmd/boostx/stats_cmd.go) that does the protocol check along with some other info. We're just missing the ability to aggregate that data with deal data. We currently run this as a cronjob on @nonsense's SP.

**Comment by frrist** [comment]
Hey @jacobheun, sorry for the slowness here. I have a draft that should fulfill most of the requirements in #1048. If someone from your team can take it over the finish line, that would be great. Couple of questions on requirements (that we can flesh out more in the PR draft):
1. If a miner doesn't advertise multiaddress in its on-chain MinerInfo structure, should it be omitted from the results?
2. If a miner does advertise multiaddress but can not be connected, should it also be omitted? Alternativly the reason for failing to connect could be persisted, unsure if that's useful.
3. If a miner fails to reply with any supported protocols or its agent version, should the reason for the failure be persisted?

**Comment by nonsense** [comment]
Thanks @frrist , I checked the commit, and in general it looks good to me. To answer your questions:

1. Yes, if they don't advertise a multi-address, we don't consider them and we omit them.
2. Yes, should be omitted. I'd be nice to persist the error, i.e. know that we can't connect to them, so that we can do stats on how many miners are advertising addresses that we can't connect to.
3. Same as 2 -- we omit them, but record the error message as it is good to know the error buckets different miners fall into.

---

For reference based on our current crawler:

```
Total SPs on chain:  589372
Total SPs with minimum power (I believe 10 TiB of power):  3932
SPs with no on-chain multiaddress: 2664
Total Lotus Markets nodes: 513
Total Boost nodes: 44
Total Boost raw power: 63756796644294656
Total Boost quality adj power: 147599634408243200
```

I'd be good to cross-reference our results from the results of Lily, once the code has been merged and we have it deployed.
